package main

import (
	"go/doc/comment"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const siteCSS = `:root {
  color-scheme: light dark;
  --bg: #f8f8f5;
  --fg: #161616;
  --muted: #656565;
  --border: #deded8;
  --panel: #ffffff;
  --accent: #2558d4;
  --code-bg: #f1f1ed;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #111111;
    --fg: #f3f3ef;
    --muted: #a7a7a0;
    --border: #30302c;
    --panel: #171717;
    --accent: #8eadff;
    --code-bg: #20201c;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 16px/1.55 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.shell {
  display: grid;
  grid-template-columns: minmax(220px, 280px) minmax(0, 1fr);
  min-height: 100vh;
}
aside {
  border-right: 1px solid var(--border);
  padding: 28px 22px;
  background: var(--panel);
}
main {
  max-width: 1040px;
  padding: 44px min(6vw, 72px);
}
.brand { font-weight: 700; margin: 0 0 8px; }
.module { color: var(--muted); font-size: 0.9rem; word-break: break-all; }
.nav { list-style: none; margin: 24px 0 0; padding: 0; }
.nav li { margin: 6px 0; }
h1, h2, h3 { line-height: 1.2; }
h1 { font-size: clamp(2rem, 4vw, 3rem); margin: 0 0 12px; }
h2 { margin-top: 44px; padding-top: 20px; border-top: 1px solid var(--border); }
h3 { margin-top: 28px; }
.import-path, .synopsis, .meta { color: var(--muted); }
.card {
  display: block;
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 16px;
  margin: 12px 0;
  background: var(--panel);
}
pre {
  overflow-x: auto;
  padding: 14px;
  border-radius: 8px;
  background: var(--code-bg);
  border: 1px solid var(--border);
}
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.doc { max-width: 78ch; }
.field-list { padding-left: 18px; }
.field-list li { margin: 8px 0; }
@media (max-width: 780px) {
  .shell { display: block; }
  aside { border-right: 0; border-bottom: 1px solid var(--border); }
  main { padding: 28px 20px; }
}`

var slugCleaner = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)

func writeSite(cfg *config, snap *snapshot) error {
	outDir := cfg.out
	if outDir == "" {
		outDir = "site"
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	if err := writeSnapshot(filepath.Join(outDir, "sourcey-godoc.json"), snap); err != nil {
		return err
	}
	if err := writeFile(outDir, "sourcey-godoc.css", siteCSS); err != nil {
		return err
	}
	if err := writeFile(outDir, "index.html", renderIndex(cfg, snap)); err != nil {
		return err
	}
	for _, pkg := range snap.Packages {
		if err := writeFile(outDir, packageFile(pkg, snap.ModulePath), renderPackage(cfg, snap, pkg)); err != nil {
			return err
		}
	}
	if err := writeFile(outDir, "llms.txt", renderLLMSText(cfg, snap)); err != nil {
		return err
	}
	if err := writeFile(outDir, "llms-full.txt", renderLLMSFull(cfg, snap)); err != nil {
		return err
	}
	return nil
}

func writeFile(root, rel, text string) error {
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(text), 0o644)
}

func renderIndex(cfg *config, snap *snapshot) string {
	title := siteTitle(cfg, snap)
	var body strings.Builder
	body.WriteString(`<h1>`)
	body.WriteString(esc(title))
	body.WriteString(`</h1>`)
	if snap.ModulePath != "" {
		body.WriteString(`<p class="module"><code>`)
		body.WriteString(esc(snap.ModulePath))
		body.WriteString(`</code></p>`)
	}
	body.WriteString(`<p class="synopsis">Native Go package documentation generated by sourcey-godoc.</p>`)
	for _, pkg := range snap.Packages {
		body.WriteString(`<a class="card" href="`)
		body.WriteString(esc(packageFile(pkg, snap.ModulePath)))
		body.WriteString(`"><strong>`)
		body.WriteString(esc(packageTitle(pkg, snap.ModulePath)))
		body.WriteString(`</strong>`)
		if pkg.Synopsis != "" {
			body.WriteString(`<p>`)
			body.WriteString(esc(pkg.Synopsis))
			body.WriteString(`</p>`)
		}
		body.WriteString(`<p class="import-path"><code>`)
		body.WriteString(esc(pkg.ImportPath))
		body.WriteString(`</code></p></a>`)
	}
	return page(title, snap, body.String())
}

func renderPackage(cfg *config, snap *snapshot, pkg pkgOut) string {
	var body strings.Builder
	body.WriteString(`<h1>`)
	body.WriteString(esc(packageTitle(pkg, snap.ModulePath)))
	body.WriteString(`</h1><p class="import-path"><code>import "`)
	body.WriteString(esc(pkg.ImportPath))
	body.WriteString(`"</code></p>`)
	if pkg.Doc != "" {
		body.WriteString(`<div class="doc">`)
		body.WriteString(renderDoc(pkg.Doc))
		body.WriteString(`</div>`)
	}
	if len(pkg.Consts) > 0 {
		body.WriteString(`<h2 id="constants">Constants</h2>`)
		body.WriteString(renderValues("const", pkg.Consts))
	}
	if len(pkg.Vars) > 0 {
		body.WriteString(`<h2 id="variables">Variables</h2>`)
		body.WriteString(renderValues("var", pkg.Vars))
	}
	if len(pkg.Funcs) > 0 {
		body.WriteString(`<h2 id="functions">Functions</h2>`)
		for _, fn := range pkg.Funcs {
			body.WriteString(renderFunc(fn))
		}
	}
	if len(pkg.Types) > 0 {
		body.WriteString(`<h2 id="types">Types</h2>`)
		for _, typ := range pkg.Types {
			body.WriteString(renderType(typ))
		}
	}
	if len(pkg.Examples) > 0 {
		body.WriteString(`<h2 id="examples">Examples</h2>`)
		for _, ex := range pkg.Examples {
			body.WriteString(renderExample(ex))
		}
	}
	return page(packageTitle(pkg, snap.ModulePath), snap, body.String())
}

func renderValues(kind string, values []valueOut) string {
	seen := map[string]bool{}
	var body strings.Builder
	for _, value := range values {
		body.WriteString(`<section id="`)
		body.WriteString(esc(kind + "-" + symbolSlug(value.Name)))
		body.WriteString(`">`)
		if value.Doc != "" {
			body.WriteString(`<div class="doc">`)
			body.WriteString(renderDoc(value.Doc))
			body.WriteString(`</div>`)
		}
		if !seen[value.Declaration] {
			seen[value.Declaration] = true
			body.WriteString(codeBlock(value.Declaration))
		}
		body.WriteString(`</section>`)
	}
	return body.String()
}

func renderFunc(fn funcOut) string {
	var body strings.Builder
	body.WriteString(`<section id="func-`)
	body.WriteString(esc(symbolSlug(fn.Name)))
	body.WriteString(`"><h3>`)
	body.WriteString(esc(fn.Signature))
	body.WriteString(`</h3>`)
	if fn.Doc != "" {
		body.WriteString(`<div class="doc">`)
		body.WriteString(renderDoc(fn.Doc))
		body.WriteString(`</div>`)
	}
	for _, ex := range fn.Examples {
		body.WriteString(renderExample(ex))
	}
	body.WriteString(`</section>`)
	return body.String()
}

func renderType(typ typeOut) string {
	var body strings.Builder
	body.WriteString(`<section id="type-`)
	body.WriteString(esc(symbolSlug(typ.Name)))
	body.WriteString(`"><h3>type `)
	body.WriteString(esc(typ.Name))
	body.WriteString(`</h3>`)
	if typ.Doc != "" {
		body.WriteString(`<div class="doc">`)
		body.WriteString(renderDoc(typ.Doc))
		body.WriteString(`</div>`)
	}
	body.WriteString(codeBlock(typ.Declaration))
	if len(typ.Fields) > 0 {
		heading := "Fields"
		if typ.Kind == "interface" {
			heading = "Methods"
		}
		body.WriteString(`<h4>`)
		body.WriteString(heading)
		body.WriteString(`</h4><ul class="field-list">`)
		for _, field := range typ.Fields {
			body.WriteString(`<li><code>`)
			body.WriteString(esc(field.Name))
			if !field.Embedded && field.Type != "" {
				body.WriteString(` `)
				body.WriteString(esc(field.Type))
			}
			body.WriteString(`</code>`)
			if field.Tag != "" {
				body.WriteString(` <code>`)
				body.WriteString(esc("`" + field.Tag + "`"))
				body.WriteString(`</code>`)
			}
			if field.Doc != "" {
				body.WriteString(`<div class="doc">`)
				body.WriteString(renderDoc(field.Doc))
				body.WriteString(`</div>`)
			}
			body.WriteString(`</li>`)
		}
		body.WriteString(`</ul>`)
	}
	for _, method := range typ.Methods {
		body.WriteString(renderFunc(method))
	}
	for _, ex := range typ.Examples {
		body.WriteString(renderExample(ex))
	}
	body.WriteString(`</section>`)
	return body.String()
}

func renderExample(ex exOut) string {
	var body strings.Builder
	body.WriteString(`<details><summary>Example`)
	if ex.Suffix != "" {
		body.WriteString(`: `)
		body.WriteString(esc(strings.ReplaceAll(ex.Suffix, "_", " ")))
	}
	body.WriteString(`</summary>`)
	if ex.Doc != "" {
		body.WriteString(`<div class="doc">`)
		body.WriteString(renderDoc(ex.Doc))
		body.WriteString(`</div>`)
	}
	body.WriteString(codeBlock(ex.Code))
	if ex.Output != "" {
		body.WriteString(`<p class="meta">Output:</p>`)
		body.WriteString(codeBlock(ex.Output))
	}
	body.WriteString(`</details>`)
	return body.String()
}

func page(title string, snap *snapshot, body string) string {
	var nav strings.Builder
	nav.WriteString(`<li><a href="index.html">Overview</a></li>`)
	for _, pkg := range snap.Packages {
		nav.WriteString(`<li><a href="`)
		nav.WriteString(esc(packageFile(pkg, snap.ModulePath)))
		nav.WriteString(`">`)
		nav.WriteString(esc(packageTitle(pkg, snap.ModulePath)))
		nav.WriteString(`</a></li>`)
	}
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>` + esc(title) + `</title>
<link rel="stylesheet" href="sourcey-godoc.css">
</head>
<body><div class="shell">
<aside><p class="brand">sourcey-godoc</p><p class="module"><code>` + esc(snap.ModulePath) + `</code></p><ul class="nav">` + nav.String() + `</ul></aside>
<main>` + body + `</main>
</div></body>
</html>
`
}

func renderLLMSText(cfg *config, snap *snapshot) string {
	var body strings.Builder
	body.WriteString("# ")
	body.WriteString(siteTitle(cfg, snap))
	body.WriteString("\n\n")
	if snap.ModulePath != "" {
		body.WriteString("Module: `")
		body.WriteString(snap.ModulePath)
		body.WriteString("`\n\n")
	}
	for _, pkg := range snap.Packages {
		body.WriteString("- [")
		body.WriteString(packageTitle(pkg, snap.ModulePath))
		body.WriteString("](")
		body.WriteString(packageFile(pkg, snap.ModulePath))
		body.WriteString(")")
		if pkg.Synopsis != "" {
			body.WriteString(" - ")
			body.WriteString(pkg.Synopsis)
		}
		body.WriteString("\n")
	}
	return body.String()
}

func renderLLMSFull(cfg *config, snap *snapshot) string {
	var body strings.Builder
	body.WriteString("# ")
	body.WriteString(siteTitle(cfg, snap))
	body.WriteString("\n\n")
	for _, pkg := range snap.Packages {
		body.WriteString("## ")
		body.WriteString(pkg.ImportPath)
		body.WriteString("\n\n")
		if pkg.Doc != "" {
			body.WriteString(docText(pkg.Doc))
			body.WriteString("\n\n")
		}
		writeDeclarations(&body, "Constants", valueDeclarations(pkg.Consts))
		writeDeclarations(&body, "Variables", valueDeclarations(pkg.Vars))
		writeDeclarations(&body, "Functions", funcDeclarations(pkg.Funcs))
		writeDeclarations(&body, "Types", typeDeclarations(pkg.Types))
	}
	return body.String()
}

func writeDeclarations(body *strings.Builder, heading string, declarations []string) {
	if len(declarations) == 0 {
		return
	}
	body.WriteString("### ")
	body.WriteString(heading)
	body.WriteString("\n\n```go\n")
	for _, decl := range declarations {
		body.WriteString(decl)
		if !strings.HasSuffix(decl, "\n") {
			body.WriteString("\n")
		}
	}
	body.WriteString("```\n\n")
}

func valueDeclarations(values []valueOut) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, value := range values {
		if value.Declaration != "" && !seen[value.Declaration] {
			seen[value.Declaration] = true
			out = append(out, value.Declaration)
		}
	}
	return out
}

func funcDeclarations(funcs []funcOut) []string {
	out := make([]string, 0, len(funcs))
	for _, fn := range funcs {
		out = append(out, fn.Signature)
	}
	sort.Strings(out)
	return out
}

func typeDeclarations(types []typeOut) []string {
	out := make([]string, 0, len(types))
	for _, typ := range types {
		out = append(out, typ.Declaration)
	}
	sort.Strings(out)
	return out
}

func siteTitle(cfg *config, snap *snapshot) string {
	if cfg.title != "" {
		return cfg.title
	}
	if snap.ModulePath != "" {
		return snap.ModulePath
	}
	return "Go API"
}

func packageTitle(pkg pkgOut, modulePath string) string {
	rel := relativePackage(pkg.ImportPath, modulePath)
	if rel == "." || rel == "" {
		return pkg.ImportPath
	}
	return rel
}

func packageFile(pkg pkgOut, modulePath string) string {
	rel := relativePackage(pkg.ImportPath, modulePath)
	if rel == "." || rel == "" {
		return "package-root.html"
	}
	return "pkg-" + slugCleaner.ReplaceAllString(strings.ReplaceAll(rel, "/", "-"), "") + ".html"
}

func relativePackage(importPath, modulePath string) string {
	if modulePath == "" {
		return importPath
	}
	if importPath == modulePath {
		return "."
	}
	return strings.TrimPrefix(importPath, modulePath+"/")
}

func renderDoc(text string) string {
	var parser comment.Parser
	doc := parser.Parse(text)
	var printer comment.Printer
	return string(printer.HTML(doc))
}

func docText(text string) string {
	var parser comment.Parser
	doc := parser.Parse(text)
	var printer comment.Printer
	return strings.TrimSpace(string(printer.Text(doc)))
}

func codeBlock(text string) string {
	return "<pre><code>" + esc(text) + "</code></pre>"
}

func symbolSlug(name string) string {
	return slugCleaner.ReplaceAllString(name, "_")
}

func esc(text string) string {
	return html.EscapeString(text)
}
